#
# Copyright (c) 2022 alandefreitas (alandefreitas@gmail.com)
#
# Distributed under the Boost Software License, Version 1.0.
# https://www.boost.org/LICENSE_1_0.txt
#

name: Publish Docs

on:
  push:
    branches:
      - master

jobs:
  generateDOC:
    name: Publish Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Contributors
        uses: akhilmhdh/contributors-readme-action@v2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          image_size: 100
          columns_per_row: 6
          readme_path: docs/acknowledgments.md
        continue-on-error: true
      - name: Install doxygen
        run: sudo apt-get install doxygen
      - name: Generate doxygen XML
        run: doxygen
        working-directory: ./docs
      - name: Download doxybook2
        uses: carlosperate/download-file-action@v1.0.3
        id: download-doxybook2
        with:
          file-url: 'https://github.com/matusnovak/doxybook2/releases/download/v1.4.0/doxybook2-linux-amd64-v1.4.0.zip'
          file-name: 'doxybook2.zip'
          location: './docs'
      - name: Unzip doxybook2
        run: |
          unzip doxybook2.zip
          rm -f doxybook2.zip
          sudo chmod +x ./bin/doxybook2
          mkdir reference
          ls
        working-directory: ./docs
      - name: Generate Doxybook
        run: ./bin/doxybook2 --input ./xml --output reference --config .doxybook/config.json --templates .doxybook/templates
        working-directory: ./docs
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install Mkdocs Material
        run: pip install mkdocs-material
      - name: Install Mermaid for Mkdocs
        run: pip install mkdocs-mermaid2-plugin
      - name: Install Macros for Mkdocs
        run: pip install mkdocs-macros-plugin
      - name: Deploy mkdocs to gh-pages branch
        run: mkdocs gh-deploy --force